services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
  app:
    image: my-node-app
    ports:
      - 13000:3000
    volumes:
      - ./:/app
    depends_on:
      - db
  develop:
    extends: app
    build: .
    command: npm run dev
    volumes:
      - ./:/app
